server:
  port: 8088
  servlet:
    context-path: /filemove/

spring:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource

#测试
dynamic:
  datasource:
    cd:
      url: jdbc:oracle:thin:@172.29.251.206:1521:ora750ab
      username: eistrong
      password: eistrong
    lq:
      url: jdbc:oracle:thin:@172.29.251.46:1521:orcl
      username: sysdeerp
      password: yc$2015

#正式
#dynamic:
#  datasource:
#    cd:
#      url: jdbc:oracle:thin:@172.25.17.29:1521/pdbcore
#      username: sysdeerp
#      password: d#41hsal
#    lq:
#      url: jdbc:oracle:thin:@172.25.17.29:1521/pdblq
#      username: sysdeerp
#      password: yc$2012


mybatis:
  #配置SQL映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置别名
  type-aliases-package: com.funi.filemove.dao
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true


# 打印sql
logging:
  level:
    com.funi.filemove.dao: debug


